use_frameworks!

target 'EmptyP0d_Example' do
  pod 'EmptyP0d', :path => '../'

  target 'EmptyP0d_Tests' do
    inherit! :search_paths

#  pod 'Quick', '~> 1.0.0'
#  pod 'Nimble', '~> 5.1.1'
  pod 'Quick', :git => 'https://github.com/Quick/Quick'
  pod 'Nimble', :git => 'https://github.com/Quick/Nimble'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
